### ISSUE TITLE
what does '-s 2.828' mean?

### ISSUE THREAD

**Issue by BiaoLiu2017** [realbigws/cwDTW#3]
It said in readme "#-> 2. generate coarsening signal via peak-pick on CWT spectrum.
./sig2peak -i example/002a08b9-0248-4929-9759-2d5c0942076d.seqsig -o 002a08b9-0248-4929-9759-2d5c0942076d.peak_seqsig -s 2.828 -z 1".
But I can't find out what '-s 2.828' means. What does the argument '-s' mean and why it is 0.282?

**Comment by realbigws** [comment]
2.828 indicates 2*sqrt(2)

**Comment by BiaoLiu2017** [comment]
haha, I see.
thanks
